### ISSUE TITLE
ASCOM.SynScanMobile.Telescope Issueu

### ISSUE THREAD

**Issue by ScrambledEggs123** [ascomghostdrivers/legacydrivers#2]
I seem to be having an issue with this driver. It connects the first time and then shortly disconnects and the device can no longer be located. 
I have tried to reinstall the driver and synscan app and I have tried 2 PC's. I am now stuck. 

Here is the info from the ASCOM app. 
Create              Creating device
Connected           Connecting to device
Error               ASCOM.DriverException: No device found
   at ASCOM.SynScanMobile.Telescope.set_Connected(Boolean value)
   at CallSite.Target(Closure , CallSite , Object , Boolean )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at ASCOM.DriverConnect.ConnectForm.btnConnect_Click(Object sender, EventArgs e) in C:\ASCOM Build\Export\ASCOM.DriverConnect\ConnectForm.cs:line 268
Dispose             Disposing of device
Dispose             Completed disposal
ReleaseComObject    Releasing COM instance
GC Collect          Starting garbage collection
GC Collect          Completed garbage collection

**Comment by Peter-Simpson** [comment]
Hi,

I think this post is in the wrong place. I presume that you are referring to the SkyWatcher SynScan app that can be downloaded from [here](https://skywatcher.com/download/software/ascom-driver/)? This repository houses ASCOM drivers which are no longer supported by their authors and cannot be supported by the Platform team.

You may find help by posting on Cloudy Nights or on the [ASCOM Talk](https://ascomtalk.groups.io/g/Help/topics) forum where other SynScan users may be able to help you.

Best wishes, Peter
